/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3TlxP0H2Mhb
 */
import { Button } from "@/components/ui/button";

export function Preview({
 name,
 type,
 fileUrl,
}: {
 name?: string;
 type?: string;
 fileUrl?: string;
}) {
 const indexOfSlash = type?.indexOf("/");
 const extractType = type?.substring(0, indexOfSlash);
 return (
  <div className="grid md:grid-cols-2 gap-6 items-start max-w-6xl py-6">
   {extractType === "image" ? (
    <div className="grid gap-4 items-start">
     <div className="font-bold text-2xl sm:text-3xl">Image Preview</div>
     <img
      alt={name}
      src={fileUrl}
      className="aspect-square object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
      height={600}
      width={600}
     />
    </div>
   ) : (
    <div className="grid gap-4 items-start">
     <h1 className="font-bold text-2xl sm:text-3xl">Video Preview</h1>
     <span className="aspect-[16/9] w-full overflow-hidden rounded-md bg-muted" />
    </div>
   )}
   <div className="flex justify-center w-full"></div>
  </div>
 );
}
